macro gen_dummy_cmps [cmd] {
forward
  cmp rax, Cmd#cmd#CsReq
  je .#cmd#_dummy_branch
}

macro gen_dummy_branches [cmd] {
forward
.#cmd#_dummy_branch:
  mov r8, 0 ; r8 = body_len
  mov r9, Cmd#cmd#ScRsp
  jmp .send_rsp
}

macro paste_dummy_cmps {
  gen_dummy_cmps GetBasicInfo, GetMarkItemList, GetPlayerBoardData, GetCurAssist, GetAllLineupData, GetAllServerPrefsData, GetActivityScheduleConfig, GetMissionData, GetQuestData, GetCurChallenge, GetRogueCommonDialogueData, GetRogueInfo, GetRogueHandbookData, GetRogueEndlessActivityData, ChessRogueQuery, RogueTournQuery, SyncClientResVersion, DailyFirstMeetPam, GetBattleCollegeData, GetNpcStatus, GetSecretKeyInfo, GetHeartDialInfo, GetVideoVersionKey, GetCurBattleInfo, HeliobusActivityData, GetEnteredScene, GetAetherDivideInfo, GetMapRotationData, GetRogueCollection, GetRogueExhibition, PlayerReturnInfoQuery, PlayerLoginFinish, GetLevelRewardTakenList, GetMainMissionCustomValue, GetMaterialSubmitActivityData, RogueTournGetCurRogueCocoonInfo, RogueMagicQuery, MusicRhythmData, GetFriendApplyListInfo, GetChatFriendHistory, GetFriendLoginInfo, GetFriendDevelopmentInfo, GetFriendRecommendListInfo, SwitchHandData, RogueArcadeGetInfo, GetMissionMessageInfo, TrainPartyGetData, QueryProductInfo, GetPamSkinData, GetRogueScoreRewardInfo, GetQuestRecord, GetDailyActiveInfo, GetChessRogueNousStoryInfo, CommonRogueQuery, GetFightActivityData, GetStarFightData, GetMultipleDropInfo, GetPlayerReturnMultiDropInfo, GetShareData, GetTreasureDungeonActivityData, EvolveBuildQueryInfo, GetAlleyInfo, GetAetherDivideChallengeInfo, GetStrongChallengeActivityData, GetOfferingInfo, ClockParkGetInfo, GetGunPlayData, GetTrackPhotoActivityData, GetSwordTrainingData, GetFightFestData, DifficultyAdjustmentGetData, SpaceZooData, GetExpeditionData, TravelBrochureGetData, RaidCollectionData, GetRaidInfo, GetLoginActivity, GetTrialActivityData, GetJukeboxData, GetMuseumInfo, GetTelevisionActivityData, GetTrainVisitorRegister, GetBoxingClubInfo, TextJoinQuery, GetLoginChatInfo, GetFeverTimeActivityData, GetSummonActivityData, TarotBookGetData, GetMarkChest, MatchThreeGetData, UpdateTrackMainMissionId, GetNpcMessageGroup, GetAllSaveRaid, GetAssistHistory, GetEraFlipperData, GetRechargeGiftInfo, GetRechargeBenefitInfo, RelicSmartWearGetPlan, RelicSmartWearGetPinRelic, SetGrowthTargetAvatar, GetElfRestaurantData, FateQuery, GetPlanetFesData, ParkourGetData, MatchThreeV2GetData, GetMonopolyInfo, MonopolyGetRegionProgress, GetMbtiReport, DrinkMakerCheersGetData, GetDrinkMakerData, ChimeraGetData, MarbleGetData, GetPreAvatarActivityList, GetArchiveData, GetUnreleasedBlockInfo, SceneEntityMove
}

macro paste_dummy_branches {
  gen_dummy_branches GetBasicInfo, GetMarkItemList, GetPlayerBoardData, GetCurAssist, GetAllLineupData, GetAllServerPrefsData, GetActivityScheduleConfig, GetMissionData, GetQuestData, GetCurChallenge, GetRogueCommonDialogueData, GetRogueInfo, GetRogueHandbookData, GetRogueEndlessActivityData, ChessRogueQuery, RogueTournQuery, SyncClientResVersion, DailyFirstMeetPam, GetBattleCollegeData, GetNpcStatus, GetSecretKeyInfo, GetHeartDialInfo, GetVideoVersionKey, GetCurBattleInfo, HeliobusActivityData, GetEnteredScene, GetAetherDivideInfo, GetMapRotationData, GetRogueCollection, GetRogueExhibition, PlayerReturnInfoQuery, PlayerLoginFinish, GetLevelRewardTakenList, GetMainMissionCustomValue, GetMaterialSubmitActivityData, RogueTournGetCurRogueCocoonInfo, RogueMagicQuery, MusicRhythmData, GetFriendApplyListInfo, GetChatFriendHistory, GetFriendLoginInfo, GetFriendDevelopmentInfo, GetFriendRecommendListInfo, SwitchHandData, RogueArcadeGetInfo, GetMissionMessageInfo, TrainPartyGetData, QueryProductInfo, GetPamSkinData, GetRogueScoreRewardInfo, GetQuestRecord, GetDailyActiveInfo, GetChessRogueNousStoryInfo, CommonRogueQuery, GetFightActivityData, GetStarFightData, GetMultipleDropInfo, GetPlayerReturnMultiDropInfo, GetShareData, GetTreasureDungeonActivityData, EvolveBuildQueryInfo, GetAlleyInfo, GetAetherDivideChallengeInfo, GetStrongChallengeActivityData, GetOfferingInfo, ClockParkGetInfo, GetGunPlayData, GetTrackPhotoActivityData, GetSwordTrainingData, GetFightFestData, DifficultyAdjustmentGetData, SpaceZooData, GetExpeditionData, TravelBrochureGetData, RaidCollectionData, GetRaidInfo, GetLoginActivity, GetTrialActivityData, GetJukeboxData, GetMuseumInfo, GetTelevisionActivityData, GetTrainVisitorRegister, GetBoxingClubInfo, TextJoinQuery, GetLoginChatInfo, GetFeverTimeActivityData, GetSummonActivityData, TarotBookGetData, GetMarkChest, MatchThreeGetData, UpdateTrackMainMissionId, GetNpcMessageGroup, GetAllSaveRaid, GetAssistHistory, GetEraFlipperData, GetRechargeGiftInfo, GetRechargeBenefitInfo, RelicSmartWearGetPlan, RelicSmartWearGetPinRelic, SetGrowthTargetAvatar, GetElfRestaurantData, FateQuery, GetPlanetFesData, ParkourGetData, MatchThreeV2GetData, GetMonopolyInfo, MonopolyGetRegionProgress, GetMbtiReport, DrinkMakerCheersGetData, GetDrinkMakerData, ChimeraGetData, MarbleGetData, GetPreAvatarActivityList, GetArchiveData, GetUnreleasedBlockInfo, SceneEntityMove
}
